<footer id="footer" class="page-footer font-small blue pt-4 mt-4">
   <!-- Footer Links -->
   <div style="background-color:#151313; color:white;" class="container-fluid text-center text-md-left">
      <!-- Grid row -->
      <div class="row">
         <!-- Grid column -->
         <div class="col-md-6 mt-md-0 mt-3">
            <!-- Content -->
            <h5 class="text-uppercase" style="padding-top:20px;">Mount Douglas Secondary School</h5>
            <p>Computer Science 12 Photo Gallery</p>
         </div>
         <!-- Grid column -->
         <h6><a href="#topofpage" style="padding:19px;color:white; right:0px;" class="text-uppercase">Top of Page</a></h6>
         <hr class="clearfix w-100 d-md-none pb-3">
         <!-- Grid column -->
         <div class="col-md-6 mb-md-0 mb-3">
            <!-- Links -->
            <h5 class="text-uppercase">Pages</h5>
            <!-- <ul class="list-unstyled"> -->
            <a href="index.php">Gallery</a> &nbsp;&nbsp;&nbsp;
            <a href="form.php">Image Upload</a>&nbsp;&nbsp;&nbsp;
            <a href="approval.php">Approval</a>&nbsp;&nbsp;&nbsp;
            <a href="moderator.php">Moderator</a>
         </div>
         <!-- Grid column -->
      </div>
      <!-- Grid row -->
   </div>
   <!-- Footer Links -->
   <!-- Copyright -->
   <div id="copyright" class="footer-copyright text-center py-3">2018 Copyright:<br>
      Liam Dwyer and Anish Sivakumar
   </div>
   <!-- Copyright -->
</footer>
<!-- Footer -->
</div>
</body>
</html>